---
- name: Instalación de Nginx
  hosts: localhost
  tasks:
    - name: Instalando el paquete nginx
      yum:
        name: nginx
        state: latest
    - name: Servicio Nginx arrancado
      service: 
        name: nginx
        state: started
        enabled: true
    - name: Instalando elinks
      package:
        name: elinks
        state: latest
    - name: Crea el directori
      file:
        name: /var/www/html
        state: directory
    - name: Copia el fichero index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'
...
