---
- hosts: redis
  tasks:
  - name: copy rpms to host
    copy: 
      src: files/redis/ 
      dest: /tmp
  - name: install redis
    yum: 
      name: "/tmp/{{ item|basename }}"
      disable_gpg_check: yes
    with_fileglob: files/redis/*rpm
